#!/bin/bash
set -eu

# Generated by lctl - Lambda Control Tool
# Function: test_lambda
# Generated at: 2025-07-17T18:33:59.187Z

# Create deployment package
cd functions
echo "Creating deployment package..."
rm -f lambda.zip
zip -r lambda.zip "."
mv lambda.zip ../
cd ..

# Lambda関数の存在を確認
if aws lambda get-function --function-name test_lambda &> /dev/null; then
    echo "Updating existing Lambda function: test_lambda"
    aws lambda update-function-code --function-name test_lambda --zip-file fileb://lambda.zip | jq .

    # 設定の更新
    aws lambda update-function-configuration --function-name test_lambda \
        --runtime python3.12 \
        --handler test_lambda.handler \
        --role arn:aws:iam::123456789012:role/lambda-execution-role \
        --timeout 3 \
        --memory-size 128 \
        --architectures x86_64 | jq .

    

    rm lambda.zip
    exit 0
fi

echo "Creating new Lambda function: test_lambda"
aws lambda create-function --function-name test_lambda \
    --zip-file fileb://lambda.zip \
    --handler test_lambda.handler \
    --runtime python3.12 \
    --architectures x86_64 \
    --timeout 3 \
    --memory-size 128 \
    --role arn:aws:iam::123456789012:role/lambda-execution-role | jq .




# ロググループが存在しなければ作成する
if ! aws logs describe-log-groups \
    --log-group-name-prefix /aws/lambda/test_lambda \
    --query "logGroups[?logGroupName=='/aws/lambda/test_lambda'].logGroupName" \
    --output text | grep -q "^/aws/lambda/test_lambda$"; then
    echo "Creating log group for test_lambda"
    aws logs create-log-group --log-group-name /aws/lambda/test_lambda | jq .
fi

# ログ保持期間を設定
aws logs put-retention-policy --log-group-name /aws/lambda/test_lambda --retention-in-days 7 | jq .


rm lambda.zip

echo "✅ Lambda function test_lambda deployed successfully!"
