#!/bin/bash
set -eu

# Generated by lctl - Lambda Control Tool
# Function: my_test_function
# Generated at: 2026-02-16T02:37:13.031Z

# Check for deployment package
if [ ! -f "test_lambda.zip" ]; then
  echo "Error: test_lambda.zip not found. Please run 'makezip' command first."
  exit 1
fi

# Environment Variables
ENVIRON='{"Variables":{"ENV":"development","DEBUG":"true"}}'

# Lambda関数の存在を確認
if aws lambda get-function --function-name my_test_function &> /dev/null; then
    echo "Updating existing Lambda function: my_test_function"
    aws lambda update-function-code --function-name my_test_function --zip-file fileb://test_lambda.zip | jq .
    
    # 関数がActiveになるまで待機
    aws lambda wait function-active --function-name my_test_function

    # 設定の更新
    aws lambda update-function-configuration --function-name my_test_function \
        --runtime python3.12 \
        --handler test_lambda.handler \
        --role arn:aws:iam::123456789012:role/lambda-execution-role \
        --timeout 30 \
        --memory-size 128 \
        --environment "$ENVIRON" \
        --description "Test Lambda function for lctl" | jq .
    
    # 関数がActiveになるまで待機
    aws lambda wait function-active --function-name my_test_function
else
    echo "Creating new Lambda function: my_test_function"
    aws lambda create-function --function-name my_test_function \
        --zip-file fileb://test_lambda.zip \
        --handler test_lambda.handler \
        --runtime python3.12 \
        --architectures x86_64 \
        --timeout 30 \
        --memory-size 128 \
        --role arn:aws:iam::123456789012:role/lambda-execution-role \
        --environment "$ENVIRON" \
        --description "Test Lambda function for lctl" | jq .
fi

# 共通の追加設定

# Set tags
aws lambda tag-resource --resource "$(aws lambda get-function --function-name my_test_function --query 'Configuration.FunctionArn' --output text)" --tags Environment=development,Project=lctl-test | jq .



# Add permissions
aws lambda remove-permission \
        --function-name my_test_function \
        --statement-id api-gateway-invoke 2>/dev/null || true
aws lambda add-permission \
        --function-name my_test_function \
        --statement-id api-gateway-invoke \
        --action lambda:InvokeFunction \
        --principal apigateway.amazonaws.com \
        --source-arn arn:aws:execute-api:us-east-1:123456789012:* | jq .
aws lambda remove-permission \
        --function-name my_test_function \
        --statement-id eventbridge-invoke 2>/dev/null || true
aws lambda add-permission \
        --function-name my_test_function \
        --statement-id eventbridge-invoke \
        --action lambda:InvokeFunction \
        --principal events.amazonaws.com \
        --source-arn arn:aws:events:us-east-1:123456789012:rule/test-rule | jq .
aws lambda remove-permission \
        --function-name my_test_function \
        --statement-id deploy-user-invoke 2>/dev/null || true
aws lambda add-permission \
        --function-name my_test_function \
        --statement-id deploy-user-invoke \
        --action lambda:InvokeFunction \
        --principal arn:aws:iam::123456789012:user/DeployUser | jq .
aws lambda remove-permission \
        --function-name my_test_function \
        --statement-id cross-account-invoke 2>/dev/null || true
aws lambda add-permission \
        --function-name my_test_function \
        --statement-id cross-account-invoke \
        --action lambda:InvokeFunction \
        --principal arn:aws:iam::123456789012:role/CrossAccountRole | jq .



# ロググループが存在しなければ作成する
if ! aws logs describe-log-groups \
    --log-group-name-prefix /aws/lambda/my_test_function \
    --query "logGroups[?logGroupName=='/aws/lambda/my_test_function'].logGroupName" \
    --output text | grep -q "^/aws/lambda/my_test_function$"; then
    echo "Creating log group for my_test_function"
    aws logs create-log-group --log-group-name /aws/lambda/my_test_function | jq .
fi

# ログ保持期間を設定
aws logs put-retention-policy --log-group-name /aws/lambda/my_test_function --retention-in-days 14 | jq .


rm test_lambda.zip

echo "✅ Lambda function my_test_function deployed successfully!"
